# Generated by Django 3.2.5 on 2021-07-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('business', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('taxid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
